# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoderDojo 枚方
# email: hirakata@coderdojo.com
timezone: Asia/Tokyo
description: > # this means to ignore newlines until "baseurl:"
  CoderDojo枚方は7〜17歳の子どもを対象にしたプログラミング道場です。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coderdojo-hirakata.github.io" # the base hostname & protocol for your site
twitter_username: CoderHirakata
github_username:  coderdojo-hirakata

# Build settings
markdown: kramdown

# Output
permalink:  /blog/:year/:month/:day/:title.html
